apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: hurtigveileder
  namespace: q0
  cluster: dev-sbs
  labels:
    team: paw
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: hurtigveileder/internal/isAlive
    initialDelay: 20
  readiness:
    path: hurtigveileder/internal/selftest
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: hurtigveileder/internal/metrics
  ingresses:
    - https://www-q0.nav.no/arbeid/hurtigveileder
  webproxy: true
  envFrom:
    - configmap: pto-config