on:
  push:
    branches:
      - master
name: Deploy to q on push
env:
  IMAGE_NAME: docker.pkg.github.com/navikt/paw-poc-hurtigveileder/hurtigveileder
  TZ: Europe/Amsterdam
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PRINT_PAYLOAD: true

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Create image tag
        run: echo ::set-env name=IMAGE::${IMAGE_NAME}:$(echo ${{ github.ref }} | cut -d '/' -f3).$(date '+%F-%H%M').$(echo $GITHUB_SHA | cut -c1-7) #eks pa tag  gh-actions.2020-01-08-1255.8fa4236
      - run: npm ci
      - run: npm run test
      - run: npm run now-build

      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build -t ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
      - name: deply q0 sbs
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-sbs
          RESOURCE: nais-q.yaml
          VAR: image=${{ IMAGE }}
