on:
  release:
    types: [published]
    branches: [master]
name: Test and Deploy to prod on release

env:
  IMAGE_NAME: docker.pkg.github.com/navikt/paw-poc-hurtigveileder/hurtigveileder
  TZ: Europe/Amsterdam
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      PRINT_PAYLOAD: true

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Create image tag
        run: echo ::set-env name=IMAGE::${IMAGE_NAME}:$(echo ${{ github.ref }} | cut -d '/' -f3).$(date '+%F-%H%M').$(echo $GITHUB_SHA | cut -c1-7) #eks pa tag  gh-actions.2020-01-08-1255.8fa4236
      - run: npm ci
      - run: npm run test
      - run: npm run nav-build

      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build -t ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
      - name: deply prod sbs
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: prod-sbs
          RESOURCE: nais-prod.yaml